version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_SIGNALR_SERVER=${VITE_SIGNALR_SERVER}
    volumes:
      - .:/app
      - /app/node_modules
